# Generated by Django 5.1.1 on 2024-10-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0006_product_main_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_category',
            new_name='main_cid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='sub_cid',
        ),
    ]
