# Generated by Django 5.1.1 on 2024-10-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0007_rename_main_category_product_main_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
