# Generated by Django 5.1.1 on 2024-10-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0009_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='main_cid',
        ),
    ]
