# Generated by Django 5.1.1 on 2024-10-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0012_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Krishna', null=True),
        ),
    ]
